//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanCafe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanSanPham
    {
        public int Id { get; set; }
        public Nullable<int> BanId { get; set; }
        public Nullable<int> SanPhamId { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<int> DaTinhTien { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
