//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanCafe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public int Id { get; set; }
        public int SanPhamId { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<decimal> TongTienSP { get; set; }
        public Nullable<System.DateTime> ThoiDiem { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
