//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanCafe2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int Id { get; set; }
        public int BanId { get; set; }
        public int NhanVienId { get; set; }
        public Nullable<decimal> TongTien { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
